// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TesteTecnicoEffecti.Src.Data;

#nullable disable

namespace TesteTecnicoEffecti.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250703001118_first-migration")]
    partial class firstmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TesteTecnicoEffecti.Src.Models.ItemLicitacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Aplicabilidade7174")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AplicabilidadeMargemPreferencia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("LicitacaoId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<string>("TratamentoDiferenciado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UnidadeFornecimento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LicitacaoId");

                    b.ToTable("ItensLicitacao", (string)null);
                });

            modelBuilder.Entity("TesteTecnicoEffecti.Src.Models.Licitacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CodigoUASG")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("DataDisponibilizacaoEdital")
                        .HasColumnType("date");

                    b.Property<DateTime>("DataEntregaProposta")
                        .HasColumnType("date");

                    b.Property<string>("EnderecoEntrega")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Fax")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<TimeSpan>("HoraEntregaProposta")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraFimEdital")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraInicioEdital")
                        .HasColumnType("time");

                    b.Property<string>("Instituicao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NumeroPregao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Objeto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Orgao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoUASG");

                    b.HasIndex("NumeroPregao");

                    b.ToTable("Licitacoes", (string)null);
                });

            modelBuilder.Entity("TesteTecnicoEffecti.Src.Models.ItemLicitacao", b =>
                {
                    b.HasOne("TesteTecnicoEffecti.Src.Models.Licitacao", "Licitacao")
                        .WithMany("Itens")
                        .HasForeignKey("LicitacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Licitacao");
                });

            modelBuilder.Entity("TesteTecnicoEffecti.Src.Models.Licitacao", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
